export const sheetNames = {
  config: "Config",
  leads: "Leads",
  bookings: "Bookings",
  artists: "Artists",
  followUps: "FollowUps",
  interactionLog: "InteractionLog",
  reviews: "Reviews",
  giftCards: "GiftCards",
  promoCodes: "PromoCodes",
  clientPackages: "Packages",
  clientPhotos: "ClientPhotos",
  products: "Products",
  productSales: "ProductSales",
} as const;

export const leadHeaders = [
  "Lead ID",
  "Created At",
  "Source",
  "Client Name",
  "Client WhatsApp",
  "Client Instagram",
  "Event Type",
  "Event Date",
  "Event Time",
  "Location Text",
  "Distance Km",
  "Travel Time Min",
  "Outstation Flag",
  "Profile Tier",
  "Followers",
  "Client Tags",
  "AI Insight",
  "Suggested Reply",
  "Demand Count",
  "Scarcity Tag",
  "Hold Expires At",
  "Initial AI Price",
  "Final Approved Price",
  "Discount Percent",
  "Owner Decision",
  "Owner Notes",
  "Status",
  "Assigned Artist",
  "Last Contacted At",
  "Tentative Calendar Event ID",
  "Confirmed Calendar Event ID",
  "Booking ID",
  "Payment Status",
  "Quote URL",
  "Quote Generated At",
  "Quote Voided At",
  "Quote Adjustments",
  "Order Items",
  "Quote Number",
  "Quote Viewed At",
  "Quote Accepted At",
  "Referred By",
  "Lost Reason",
  "Urgency Flag",
  "Client Note",
] as const;

export const bookingHeaders = [
  "Booking ID",
  "Lead ID",
  "Booked At",
  "Client Name",
  "Client WhatsApp",
  "Event Type",
  "Event Date",
  "Event Time",
  "Venue",
  "Assigned Artist",
  "Final Price",
  "Advance Amount",
  "Balance Due",
  "Tentative Calendar Event ID",
  "Confirmed Calendar Event ID",
  "Contract URL",
  "Invoice URL",
  "Payment Status",
  "Status",
  "Contract Status",
  "Contract Sent At",
  "Invoice Generated At",
  "Reminders Sent",
  "Invoice Voided At",
  "Contract Voided At",
  "Invoice Adjustments",
  "Contract Adjustments",
  "Order Items",
  "Contract Signed At",
  "Contract Signer Name",
  "Expenses",
  "Invoice Number",
  "Payments Log",
  "Invoice Viewed At",
  "Contract Viewed At",
  "Invoice Due Date",
  "Arrived At",
  "Status Changed At",
] as const;

export const artistHeaders = [
  "Artist ID",
  "Name",
  "WhatsApp",
  "Email",
  "City",
  "Skill Level",
  "Price Multiplier",
  "Luxury Eligible",
  "Primary Calendar ID",
  "Active",
  "Bio",
] as const;

export const followUpHeaders = [
  "Log ID",
  "Lead ID",
  "Scheduled At",
  "Sent At",
  "Type",
  "Channel",
  "Message Preview",
  "Status",
] as const;

export const interactionHeaders = [
  "Log ID",
  "Lead ID",
  "Direction",
  "Channel",
  "Actor",
  "Message",
  "AI Summary",
  "Created At",
] as const;

export const reviewHeaders = [
  "Review ID",
  "Lead ID",
  "Client Name",
  "Event Date",
  "Request Sent At",
  "Reminder Sent At",
  "Review Link Clicked",
  "Review Confirmed",
  "Notes",
] as const;

export const giftCardHeaders = [
  "Card ID",
  "Code",
  "Amount",
  "Message",
  "Purchaser Name",
  "Purchaser Email",
  "Purchaser WhatsApp",
  "Redeemed By Lead ID",
  "Redeemed At",
  "Created At",
  "Status",
] as const;
