import type { WorkspaceConfig } from "./types.js";

export function buildDefaultConfig(profile: { email: string; name: string }): WorkspaceConfig {
  return {
    businessName: "",
    ownerName: profile.name,
    ownerEmail: profile.email,
    ownerWhatsApp: "",
    city: "",
    instagramHandle: "",
    aiLanguage: "English",
    aiSignOff: "With love,",
    basePriceBridal: 25000,
    basePriceEngagement: 15000,
    basePriceReception: 18000,
    basePriceParty: 8000,
    basePriceShoot: 10000,
    basePriceOther: 8000,
    multiplierJan: 1,
    multiplierFeb: 1.2,
    multiplierMar: 1.1,
    multiplierApr: 1,
    multiplierMay: 0.9,
    multiplierJun: 0.9,
    multiplierJul: 0.9,
    multiplierAug: 0.9,
    multiplierSep: 1,
    multiplierOct: 1.2,
    multiplierNov: 1.5,
    multiplierDec: 1.5,
    holdExpiryHours: 6,
    scarcityThresholdSoft: 4,
    scarcityThresholdHard: 7,
    travelWithinCity: 0,
    travelNearbyCity: 2000,
    travelOutstation: 5000,
    travelOutstationThresholdKm: 100,
    profileLowMultiplier: 1,
    profileMidMultiplier: 1.1,
    profileHighMultiplier: 1.25,
    profileHighMinFollowers: 10000,
    advancePercentage: 30,
    upiId: "",
    qrImageUrl: "",
    paymentTerms:
      "Advance payment of 30% is required to confirm the booking. Balance is due on the event day.",
    googleReviewLink: "",
    contractTemplateUrl: "",
    confirmedCalendarId: "primary",
    tentativeCalendarId: "",
    bookingPageEnabled: "Yes",
    bookingLeadTimeDays: 1,
    bookingMaxAdvanceDays: 365,
    bookingWeeklyOffDays: "",
    bookingBlockedDates: "",
    bookingMaxPerDay: 0,
    bookingConfirmTemplate: "",
    bookingConfirmTemplateLang: "en",
    approvalTemplate: "",
    approvalTemplateLang: "en",
    reminderTemplate: "",
    reminderTemplateLang: "en",
    reminderDaysBefore: "7,1",
    serviceBridalDesc: "",
    serviceEngagementDesc: "",
    serviceReceptionDesc: "",
    servicePartyDesc: "",
    serviceShootDesc: "",
    serviceOtherDesc: "",
    serviceBridalAddons: "",
    serviceEngagementAddons: "",
    serviceReceptionAddons: "",
    servicePartyAddons: "",
    serviceShootAddons: "",
    serviceOtherAddons: "",
  };
}
