import { z } from "zod";

const numberFromForm = z.coerce.number();

export const workspaceConfigSchema = z.object({
  businessName: z.string().min(1),
  ownerName: z.string().min(1),
  ownerEmail: z.string().email(),
  ownerWhatsApp: z.string().min(8),
  city: z.string().min(1),
  instagramHandle: z.string().optional().default(""),
  aiLanguage: z.string().min(1),
  aiSignOff: z.string().min(1),
  basePriceBridal: numberFromForm,
  basePriceEngagement: numberFromForm,
  basePriceReception: numberFromForm,
  basePriceParty: numberFromForm,
  basePriceShoot: numberFromForm,
  basePriceOther: numberFromForm,
  multiplierJan: numberFromForm,
  multiplierFeb: numberFromForm,
  multiplierMar: numberFromForm,
  multiplierApr: numberFromForm,
  multiplierMay: numberFromForm,
  multiplierJun: numberFromForm,
  multiplierJul: numberFromForm,
  multiplierAug: numberFromForm,
  multiplierSep: numberFromForm,
  multiplierOct: numberFromForm,
  multiplierNov: numberFromForm,
  multiplierDec: numberFromForm,
  holdExpiryHours: numberFromForm,
  scarcityThresholdSoft: numberFromForm,
  scarcityThresholdHard: numberFromForm,
  travelWithinCity: numberFromForm,
  travelNearbyCity: numberFromForm,
  travelOutstation: numberFromForm,
  travelOutstationThresholdKm: numberFromForm,
  // Distance (km) where "within city" ends and the nearby-city fee starts.
  travelNearbyThresholdKm: numberFromForm.optional().default(25),
  // Optional ₹/km mode: when > 0 it replaces the three flat tiers entirely.
  travelPerKmRate: numberFromForm.optional().default(0),
  profileLowMultiplier: numberFromForm,
  profileMidMultiplier: numberFromForm,
  profileHighMultiplier: numberFromForm,
  profileHighMinFollowers: numberFromForm,
  advancePercentage: numberFromForm,
  upiId: z.string().optional().default(""),
  qrImageUrl: z.string().optional().default(""),
  paymentTerms: z.string().min(1),
  googleReviewLink: z.string().optional().default(""),
  contractTemplateUrl: z.string().optional().default(""),
  confirmedCalendarId: z.string().min(1),
  tentativeCalendarId: z.string().min(1),
  bookingPageEnabled: z.string().optional().default("Yes"),
  bookingLeadTimeDays: numberFromForm.optional().default(1),
  bookingMaxAdvanceDays: numberFromForm.optional().default(365),
  bookingWeeklyOffDays: z.string().optional().default(""),
  bookingBlockedDates: z.string().optional().default(""),
  bookingMaxPerDay: numberFromForm.optional().default(0),
  bookingConfirmTemplate: z.string().optional().default(""),
  bookingConfirmTemplateLang: z.string().optional().default("en"),
  approvalTemplate: z.string().optional().default(""),
  approvalTemplateLang: z.string().optional().default("en"),
  notifyTeamOnBooking: z.string().optional().default("Yes"),
  teamNotifyTemplate: z.string().optional().default(""),
  teamNotifyTemplateLang: z.string().optional().default("en"),
  quoteTemplate: z.string().optional().default(""),
  quoteTemplateLang: z.string().optional().default("en"),
  invoiceTemplate: z.string().optional().default(""),
  invoiceTemplateLang: z.string().optional().default("en"),
  contractTemplate: z.string().optional().default(""),
  contractTemplateLang: z.string().optional().default("en"),
  collectionTemplate: z.string().optional().default(""),
  collectionTemplateLang: z.string().optional().default("en"),
  reminderTemplate: z.string().optional().default(""),
  reminderTemplateLang: z.string().optional().default("en"),
  reminderDaysBefore: z.string().optional().default("7,1"),
  autoPaymentReminders: z.string().optional().default("Yes"),
  // Morning push digest: today's jobs + what needs her attention.
  dailyDigest: z.string().optional().default("Yes"),
  waitlistOfferTemplate: z.string().optional().default(""),
  waitlistOfferTemplateLang: z.string().optional().default("en"),
  ownerAlertTemplate: z.string().optional().default(""),
  ownerAlertTemplateLang: z.string().optional().default("en"),
  razorpayKeyId: z.string().optional().default(""),
  razorpayKeySecret: z.string().optional().default(""),
  serviceBridalDesc: z.string().optional().default(""),
  serviceEngagementDesc: z.string().optional().default(""),
  serviceReceptionDesc: z.string().optional().default(""),
  servicePartyDesc: z.string().optional().default(""),
  serviceShootDesc: z.string().optional().default(""),
  serviceOtherDesc: z.string().optional().default(""),
  serviceBridalAddons: z.string().optional().default(""),
  serviceEngagementAddons: z.string().optional().default(""),
  serviceReceptionAddons: z.string().optional().default(""),
  servicePartyAddons: z.string().optional().default(""),
  serviceShootAddons: z.string().optional().default(""),
  serviceOtherAddons: z.string().optional().default(""),
  bookingTimeSlots: z.string().optional().default(""),
  bookingWaitlistEnabled: z.string().optional().default("No"),
  portfolioImages: z.string().optional().default(""),
  aboutText: z.string().optional().default(""),
  reviewRequestDaysAfter: z.string().optional().default(""),
  reviewTemplate: z.string().optional().default(""),
  reviewTemplateLang: z.string().optional().default("en"),
  documentTemplate: z.string().optional().default("classic"),
  quoteIntro: z.string().optional().default(""),
  cancellationPolicy: z.string().optional().default(""),
  contractTerms: z.string().optional().default(""),
  autoReplyEnabled: z.string().optional().default("No"),
  aiToneSamples: z.string().optional().default(""),
  aiToneProfile: z.string().optional().default(""),
  aiServicesContext: z.string().optional().default(""),
  aiPersonaName: z.string().optional().default(""),
  googleRating: z.string().optional().default(""),
  googleReviewCount: z.string().optional().default(""),
  quotePackages: z.string().optional().default(""),
  bookingSlug: z.string().optional().default(""),
  serviceDurations: z.string().optional().default(""),
  brandColor: z.string().optional().default(""),
  coverImageUrl: z.string().optional().default(""),
  headline: z.string().optional().default(""),
  tagline: z.string().optional().default(""),
  logoUrl: z.string().optional().default(""),
  gstNumber: z.string().optional().default(""),
  gstPercentage: z.coerce.number().min(0).max(28).optional().default(0),
  cancellationWindowDays: z.coerce.number().min(0).max(365).optional().default(7),
  cancellationFeePercent: z.coerce.number().min(0).max(100).optional().default(50),
  // Loyalty program
  loyaltyEnabled: z.string().optional().default("No"),
  loyaltyVisitsForReward: numberFromForm.optional().default(5),
  loyaltyRewardValue: numberFromForm.optional().default(500),
  loyaltyRewardNote: z.string().optional().default(""),
  // Gift cards
  giftCardsEnabled: z.string().optional().default("No"),
  // Intake / consultation forms (one per service type — comma-separated questions)
  intakeFormBridal: z.string().optional().default(""),
  intakeFormEngagement: z.string().optional().default(""),
  intakeFormReception: z.string().optional().default(""),
  intakeFormParty: z.string().optional().default(""),
  intakeFormShoot: z.string().optional().default(""),
  intakeFormOther: z.string().optional().default(""),
  // Commission / tips
  commissionDefaultPercent: numberFromForm.optional().default(0),
  tipsEnabled: z.string().optional().default("No"),
  // No-show tracking
  noShowFeePercent: numberFromForm.optional().default(0),
  noShowPolicy: z.string().optional().default(""),
  // Email channel
  emailEnabled: z.string().optional().default("No"),
  smtpHost: z.string().optional().default(""),
  smtpPort: numberFromForm.optional().default(587),
  smtpUser: z.string().optional().default(""),
  smtpPass: z.string().optional().default(""),
  smtpFrom: z.string().optional().default(""),
  // Recurring appointments
  recurringEnabled: z.string().optional().default("No"),
});

export type WorkspaceConfigInput = z.infer<typeof workspaceConfigSchema>;
