import { z } from "zod";

const numberFromForm = z.coerce.number();

export const workspaceConfigSchema = z.object({
  businessName: z.string().min(1),
  ownerName: z.string().min(1),
  ownerEmail: z.string().email(),
  ownerWhatsApp: z.string().min(8),
  city: z.string().min(1),
  instagramHandle: z.string().optional().default(""),
  aiLanguage: z.string().min(1),
  aiSignOff: z.string().min(1),
  basePriceBridal: numberFromForm,
  basePriceEngagement: numberFromForm,
  basePriceReception: numberFromForm,
  basePriceParty: numberFromForm,
  basePriceShoot: numberFromForm,
  basePriceOther: numberFromForm,
  multiplierJan: numberFromForm,
  multiplierFeb: numberFromForm,
  multiplierMar: numberFromForm,
  multiplierApr: numberFromForm,
  multiplierMay: numberFromForm,
  multiplierJun: numberFromForm,
  multiplierJul: numberFromForm,
  multiplierAug: numberFromForm,
  multiplierSep: numberFromForm,
  multiplierOct: numberFromForm,
  multiplierNov: numberFromForm,
  multiplierDec: numberFromForm,
  holdExpiryHours: numberFromForm,
  scarcityThresholdSoft: numberFromForm,
  scarcityThresholdHard: numberFromForm,
  travelWithinCity: numberFromForm,
  travelNearbyCity: numberFromForm,
  travelOutstation: numberFromForm,
  travelOutstationThresholdKm: numberFromForm,
  profileLowMultiplier: numberFromForm,
  profileMidMultiplier: numberFromForm,
  profileHighMultiplier: numberFromForm,
  profileHighMinFollowers: numberFromForm,
  advancePercentage: numberFromForm,
  upiId: z.string().optional().default(""),
  qrImageUrl: z.string().optional().default(""),
  paymentTerms: z.string().min(1),
  googleReviewLink: z.string().optional().default(""),
  contractTemplateUrl: z.string().optional().default(""),
  confirmedCalendarId: z.string().min(1),
  tentativeCalendarId: z.string().min(1),
  bookingPageEnabled: z.string().optional().default("Yes"),
  bookingLeadTimeDays: numberFromForm.optional().default(1),
  bookingMaxAdvanceDays: numberFromForm.optional().default(365),
  bookingWeeklyOffDays: z.string().optional().default(""),
  bookingBlockedDates: z.string().optional().default(""),
  bookingMaxPerDay: numberFromForm.optional().default(0),
  bookingConfirmTemplate: z.string().optional().default(""),
  bookingConfirmTemplateLang: z.string().optional().default("en"),
});

export type WorkspaceConfigInput = z.infer<typeof workspaceConfigSchema>;
